ThuVienSo Project/ThuVienSo Project/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using ThuVienSo_Project.Models;

namespace ThuVienSo_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly thuviensoContext _context;
        public INotyfService _notifyService { get; }
        public AdminCategoriesController(thuviensoContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var lsCat = _context.Danhmucs.AsNoTracking()
                .OrderByDescending(x => x.Madanhmuc);

            PagedList<Danhmuc> models = new PagedList<Danhmuc>(lsCat, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmucs
                .FirstOrDefaultAsync(m => m.Madanhmuc == id);
            if (danhmuc == null)
            {
                return NotFound();
            }

            return View(danhmuc);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Madanhmuc,Tendanhmuc")] Danhmuc danhmuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhmuc);
                await _context.SaveChangesAsync();
                _notifyService.Success("Add Success");
                return RedirectToAction(nameof(Index));
            }
            return View(danhmuc);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmucs.FindAsync(id);
            if (danhmuc == null)
            {
                return NotFound();
            }
            return View(danhmuc);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Madanhmuc,Tendanhmuc")] Danhmuc danhmuc)
        {
            if (id != danhmuc.Madanhmuc)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhmuc);
                    await _context.SaveChangesAsync();
                    _notifyService.Success("Update Success");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhmucExists(danhmuc.Madanhmuc))
                    {
                        _notifyService.Success("Error 404");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(danhmuc);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmucs
                .FirstOrDefaultAsync(m => m.Madanhmuc == id);
            if (danhmuc == null)
            {
                return NotFound();
            }

            return View(danhmuc);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhmuc = await _context.Danhmucs.FindAsync(id);
            _context.Danhmucs.Remove(danhmuc);
            await _context.SaveChangesAsync();
            _notifyService.Success("Delete Success");
            return RedirectToAction(nameof(Index));
        }

        private bool DanhmucExists(int id)
        {
            return _context.Danhmucs.Any(e => e.Madanhmuc == id);
        }
    }
}

ThuVienSo Project/ThuVienSo Project/Areas/Admin/Views/AdminCategories/Create.cshtml
@model ThuVienSo_Project.Models.Danhmuc

@{
    ViewData["Title"] = "Tạo mới Danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminCategories" asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Home" asp-controller="Admin" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <a class="breadcrumb-item" asp-area="Home" asp-controller="Admin" asp-action="AdminCategories">Danh sách danh mục</a>
                <span class="breadcrumb-item active">Tạo mới danh mục</span>
            </nav>
        </div>
    </div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Tạo mới</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
            </li>
            <li class="nav-item">
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên danh mục</label>
                        <input type="text" class="form-control" asp-for="Tendanhmuc">                    
                </div>
            </div>
        </div>
    </div>
    </div>
</form>

ThuVienSo Project/ThuVienSo Project/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model ThuVienSo_Project.Models.Danhmuc

@{
    ViewData["Title"] = "Xóa Danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Home" asp-controller="Admin" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Home" asp-controller="Admin" asp-action="AdminCategories">Danh sách danh mục</a>
            <span class="breadcrumb-item active">Thông tin danh mục</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin danh mục: @Model.Tendanhmuc</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>Mã danh mục:</td>
                        <td class="text-dark font-weight-semibold">@Model.Madanhmuc</td>
                    </tr>
                    <tr>
                        <td>Tên danh mục:</td>
                        <td>@Model.Tendanhmuc</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                             <form asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@Model.Madanhmuc">
                                <input type="hidden" asp-for="Madanhmuc"/>
                                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

ThuVienSo Project/ThuVienSo Project/Areas/Admin/Views/AdminCategories/Details.cshtml
@model ThuVienSo_Project.Models.Danhmuc

@{
    ViewData["Title"] = "Thông tin Danh mục " + Model.Tendanhmuc;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Home" asp-controller="Admin" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Home" asp-controller="Admin" asp-action="AdminCategories">Danh sách danh mục</a>
            <span class="breadcrumb-item active">Thông tin danh mục</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin danh mục: @Model.Tendanhmuc</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>Mã danh mục:</td>
                        <td class="text-dark font-weight-semibold">@Model.Madanhmuc</td>
                    </tr>
                    <tr>
                        <td>Tên danh mục:</td>
                        <td>@Model.Tendanhmuc</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

ThuVienSo Project/ThuVienSo Project/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model ThuVienSo_Project.Models.Danhmuc

@{
    ViewData["Title"] = "Chỉnh sửa Danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.Madanhmuc" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Madanhmuc" />
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Home" asp-controller="Admin" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <a class="breadcrumb-item" asp-area="Home" asp-controller="Admin" asp-action="AdminCategories">Danh sách danh mục</a>
                <span class="breadcrumb-item active">Chỉnh sửa danh mục</span>
            </nav>
        </div>
    </div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu chỉnh sửa</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
            </li>
            <li class="nav-item">
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên danh mục</label>
                        <input type="text" class="form-control" asp-for="Tendanhmuc">
                    </div>
                </div>
            </div>
        </div>
        </div>
</form>

ThuVienSo Project/ThuVienSo Project/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<ThuVienSo_Project.Models.Danhmuc>

@{
    ViewData["Title"] = "Danh mục tài liệu - page: " + @ViewBag.CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home"  class="breadcrumb-item" asp-action="Index"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Danh sách danh mục</a>
            <span class="breadcrumb-item active">Danh sách danh mục : page @ViewBag.CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-md-8">
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminCategories" asp-action="Create"> <i class="anticon anticon-plus-circle m-r-5"></i>  <span>Thêm danh mục</span> </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>Mã danh mục</th>
                        <th>Tên danh mục</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Madanhmuc</td>             
                                <td>@item.Tendanhmuc</td>
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.Madanhmuc">View</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.Madanhmuc">Edit</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.Madanhmuc">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>