ThuVienSo Project/ThuVienSo Project/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ThuVienSo.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

ThuVienSo Project/ThuVienSo Project/Areas/GiangVien/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ThuVienSo_Project.Areas.GiangVien.Controllers
{
    [Area("GiangVien")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ThuVienSo Project/ThuVienSo Project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ThuVienSo_Project.Models;

namespace ThuVienSo_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public int checklog = 0;
        private readonly thuviensoContext _context;
        public HomeController(ILogger<HomeController> logger, thuviensoContext context)
        {
            _logger = logger;
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TVS()
        {
            return View();
        }

        public IActionResult News(int id)
        {
            ViewBag.id = id;
            return View();
        }

        public IActionResult Educate(int id)
        {
            ViewBag.id = id;
            return View();
        }

        public IActionResult About(int id)
        {
            ViewBag.id = id;
            return View();
        }

        public IActionResult Contact(int id)
        {
            ViewBag.id = id;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpGet]
        public async Task<JsonResult> LoadTopRateDoc()
        {
            List<Sach> b = await _context.Saches
                .OrderByDescending(x => x.Diemdanhgia)
                .Take(4).ToListAsync();

            return Json(new { status = "ok", sachs = b });
        }
    }
}

ThuVienSo Project/ThuVienSo Project/Controllers/TailieuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ThuVienSo_Project.Helpper;
using ThuVienSo_Project.Models;

namespace ThuVienSo_Project.Controllers
{

    public class TailieuController : Controller
    {
        private readonly thuviensoContext _context;
        public TailieuController(thuviensoContext context)
        {
            _context = context;
        }
        public IActionResult Index(int page = 1, int Idmon = 0, int Madanhmuc = 0, int Manganh = 0, string Keyword = "", int idlayout=0)
        {
            ViewBag.idlayout = idlayout;
            var pageNumber = page;
            var pageSize = 7;
            List<Sach> lsBooks = new List<Sach>();
            if (Idmon != 0)
            {
                lsBooks = _context.Saches.AsNoTracking()
                    .Where(x => x.Idmon == Idmon)
                .Include(x => x.MadanhmucNavigation)
                .Include(x => x.IdmonNavigation)
                .Include(x => x.MagvNavigation)
                .OrderByDescending(x => x.Masach).ToList();
                ViewBag.CurrentCateID = Idmon;
            }
            else if (Madanhmuc != 0)
            {
                lsBooks = _context.Saches.AsNoTracking()
                    .Where(x => x.Madanhmuc == Madanhmuc)
                .Include(x => x.MadanhmucNavigation)
                .Include(x => x.IdmonNavigation)
                .Include(x => x.MagvNavigation)
                .OrderByDescending(x => x.Masach).ToList();
                ViewBag.CurrentCateID = Madanhmuc;
            }
            else if (Manganh != 0)
            {
                lsBooks = _context.Saches.AsNoTracking()
                    .Where(x => x.IdmonNavigation.Manganh == Manganh)
                .Include(x => x.MadanhmucNavigation)
                .Include(x => x.IdmonNavigation)
                .Include(x => x.MagvNavigation)
                .OrderByDescending(x => x.Masach).ToList();
                ViewBag.CurrentCateID = Manganh;
            }
            else if (String.Compare(Keyword, "", true) != 0)
            {
                lsBooks = _context.Saches.AsNoTracking()
                    .Where(x => x.Keyword.Contains(Keyword) || x.Tensach.Contains(Keyword))
                .Include(x => x.MadanhmucNavigation)
                .Include(x => x.IdmonNavigation)
                .Include(x => x.MagvNavigation)
                .OrderByDescending(x => x.Masach).ToList();
                ViewBag.CurrentCateID = Keyword;
            }
            else
            {
                lsBooks = _context.Saches.AsNoTracking()
                .Include(x => x.MadanhmucNavigation)
                .Include(x => x.IdmonNavigation)
                .Include(x => x.MagvNavigation)
                .OrderByDescending(x => x.Masach).ToList();
                ViewBag.CurrentCateID = Idmon;
            }
            PagedList<Sach> models = new PagedList<Sach>(lsBooks.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;

            ViewData["Idmon"] = new SelectList(_context.Monhocs, "Idmon", "Tenmon", Idmon);
            ViewData["Madanhmuc"] = new SelectList(_context.Danhmucs, "Madanhmuc", "Tendanhmuc", Madanhmuc);
            ViewData["Manganh"] = new SelectList(_context.Danhmucs, "Manganh", "Tennganh", Manganh);
            return View(models);
        }
        public IActionResult Filtter(int Idmon = 0, int idlayout=0)
        {
            var url = $"/Tailieu?Idmon={Idmon}&idlayout={idlayout}";
            if (Idmon == 0)
            {
                url = $"/Tailieu?idlayout={idlayout}";
            }
            return Json(new { status = "success", redirectUrl = url });
        }
        public async Task<IActionResult> Details(int? id, int idlayout)
        {
            ViewBag.idlayout = idlayout;
            if (id == null)
            {
                return NotFound();
            }

            var sach = await _context.Saches
                .Include(s => s.IdmonNavigation)
                .Include(s => s.MadanhmucNavigation)
                .Include(s => s.MagvNavigation)
                .FirstOrDefaultAsync(m => m.Masach == id);
            
            ViewBag.Context = _context;
            ViewBag.Diemdanhgia = sach.Diemdanhgia;
            ViewBag.Luotdanhgia = sach.Luotdanhgia;
            ViewBag.Capnhatdiem = 0;
            if (sach == null)
            {
                return NotFound();
            }

            return View(sach);
        }
        public string GetDataPath(string file) => $"wwwroot\\tailieu\\filetailieu\\{file}";
        public (Stream, string) Taixuong(Sach b)
        {
            var memmory = new MemoryStream();
            using var stream = new FileStream(GetDataPath(b.Filedata), FileMode.Open);
            stream.CopyTo(memmory);
            memmory.Position = 0;
            var type = Path.GetExtension(b.Filedata) switch
            {
                "pdf" => "application/pdf",
                "docx" => "application/vnd.ms-word",
                "doc" => "application/vnd.ms-word",
                "txt" => "text/plain",
                _ => "application/pdf"
            };
            return (memmory, type);
        }
        public async Task<IActionResult> Read(int id, int idlayout)
        {
            var b = await _context.Saches
             .Include(s => s.IdmonNavigation)
             .Include(s => s.MadanhmucNavigation)
             .Include(s => s.MagvNavigation)
             .FirstOrDefaultAsync(m => m.Masach == id);
            if (b == null) return NotFound();
            if (!System.IO.File.Exists(GetDataPath(b.Filedata))) return NotFound();
            b.Luottai = b.Luottai + 1;
            _context.Update(b);
            await _context.SaveChangesAsync();
            var (stream, type) = Taixuong(b);
            if (idlayout == 2) return File(stream, type, b.Filedata);
            else return Redirect("/Login?#");
            //return RedirectToAction("Details", "Tailieu", new { id = id });
        }

        [HttpPost]
        public async Task<JsonResult> SaveDanhGia(int id, double diem)
        {
            var b = await _context.Saches
                .Include(s => s.IdmonNavigation)
                .Include(s => s.MadanhmucNavigation)
                .Include(s => s.MagvNavigation)
                .FirstOrDefaultAsync(m => m.Masach == id);
            b.Diemdanhgia = diem;
            b.Luotdanhgia = b.Luotdanhgia + 1;
            _context.Update(b);
            int saveResult = await _context.SaveChangesAsync();
            if (saveResult > 0)
            {
                return Json(new { status = "ok" });
            }
            else
            {
                return Json(new { status = "err" });
            }
        }

        [HttpGet]
        public async Task<JsonResult> LoadTopRateDoc()
        {
            List<Sach> b = await _context.Saches
                .OrderByDescending(x => x.Diemdanhgia)
                .Take(3).ToListAsync();

            return Json(new { status = "ok", sachs = b });
        }
    }
}

ThuVienSo Project/ThuVienSo Project/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    int a = ViewBag.id;
    if(a==1) Layout = "~/Views/Shared/_Layout.cshtml";
    else if(a==2) Layout = "~/Views/Shared/_Layout2.cshtml";
}

<section class="about_section layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="img-box">
                        <img src="~/assets/images/about-img.png" alt="" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="detail-box">
                        <div class="heading_container">
                            <h2>About Our Bookstore</h2>
                        </div>
                        <p>
                            At cumque tenetur iste molestiae, vel eum reiciendis assumenda! Numquam, repudiandae. Consequuntur obcaecati recusandae aliquam, amet doloribus eius dolores officiis cumque? Quibusdam praesentium pariatur sapiente mollitia, amet hic iusto voluptas! Iusto
                            quo earum vitae excepturi, ipsam aliquid deleniti assumenda culpa deserunt.
                        </p>
                        <a href=""> Read More </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

ThuVienSo Project/ThuVienSo Project/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    int a = ViewBag.id;
    if(a==1) Layout = "~/Views/Shared/_Layout.cshtml";
    else if(a==2) Layout = "~/Views/Shared/_Layout2.cshtml";
}

<section class="contact_section layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-13">
                    <div class="heading_container">
                        <h2 class="">Contact Us</h2>
                    </div>
                    <form action="#">
                        <div>
                            <input type="text" placeholder="Name" />
                        </div>
                        <div>
                            <input type="email" placeholder="Email" />
                        </div>
                        <div>
                            <input type="text" placeholder="Pone Number" />
                        </div>
                        <div>
                            <input type="text" class="message-box" placeholder="Message" />
                        </div>
                        <div class="btn-box">
                            <button>SEND</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-13">
                    <div class="img-box">
                        <img src="~/assets/images/contact-img.png" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </section>

ThuVienSo Project/ThuVienSo Project/Views/Home/Educate.cshtml
@{
    ViewData["Title"] = "Educate";
    int a = ViewBag.id;
    if(a==1) Layout = "~/Views/Shared/_Layout.cshtml";
    else if(a==2) Layout = "~/Views/Shared/_Layout2.cshtml";
}
<section class="catagory_section layout_padding">
        <div class="catagory_container">
            <div class="container">
                <div class="heading_container heading_center">
                    <h2><a asp-controller="Tailieu" asp-action="Index" asp-route-idlayout=@a>Tài nguyên số</a></h2>
                    <p></p>              
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                            <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_computer.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5><a asp-controller="Tailieu" asp-action="Index" asp-route-Manganh="1" asp-route-idlayout=@a>Công nghệ thông tin</a></h5>
                            </div>
                        </div>
                        
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_book.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5><a asp-controller="Tailieu" asp-action="Index" asp-route-Manganh="2" asp-route-idlayout=@a>Khoa học cơ bản</a></h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_vtkt.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5><a asp-controller="Tailieu" asp-action="Index" asp-route-Manganh="3" asp-route-idlayout=@a>Vận tải kinh tế</a></h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_cokhi.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5><a asp-controller="Tailieu" asp-action="Index" asp-route-Manganh="4" asp-route-idlayout=@a>Cơ khí</a></h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_congtrinh.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5><a asp-controller="Tailieu" asp-action="Index" asp-route-Manganh="5" asp-route-idlayout=@a>Công trình</a></h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_dientu.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5><a asp-controller="Tailieu" asp-action="Index" asp-route-Manganh="6" asp-route-idlayout=@a>Điện tử</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

ThuVienSo Project/ThuVienSo Project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!-- slider section -->
<section class="slider_section">
        <div id="customCarousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-13">
                                <div class="detail-box">
                                    <h5>Thư viện UTC2</h5>
                                    <h1>
                                        For All Your <br /> Reading Needs
                                    </h1>
                                    <p>
                                        Cùng đến với giao diện hoàn toàn mới và tìm kiếm những cuốn sách theo ngành học của bạn. Chúng tôi sẽ cung cấp tất cả theo nhu cầu bạn đọc.
                                    </p>
                                    <a href=""> Xem thêm </a>
                                </div>
                            </div>
                            <div class="col-md-13">
                                <div class="img-box">
                                    <img src="~/assets/images/slider-img.png" alt="" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-13">
                                <div class="detail-box">
                                    <h5>Thư viện UTC2</h5>
                                    <h1>
                                        For All Your <br /> Reading Needs
                                    </h1>
                                    <p>
                                        Cùng đến với giao diện hoàn toàn mới và tìm kiếm những cuốn sách theo ngành học của bạn. Chúng tôi sẽ cung cấp tất cả theo nhu cầu bạn đọc.
                                    </p>
                                    <a href=""> Xem thêm </a>
                                </div>
                            </div>
                            <div class="col-md-13">
                                <div class="img-box">
                                    <img src="~/assets/images/slider-img.png" alt="" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-13">
                                <div class="detail-box">
                                    <h5>Thư viện UTC2</h5>
                                    <h1>
                                        For All Your <br /> Reading Needs
                                    </h1>
                                    <p>
                                        Cùng đến với giao diện hoàn toàn mới và tìm kiếm những cuốn sách theo ngành học của bạn. Chúng tôi sẽ cung cấp tất cả theo nhu cầu bạn đọc.
                                    </p>
                                    <a href=""> Xem thêm </a>
                                </div>
                            </div>
                            <div class="col-md-13">
                                <div class="img-box">
                                    <img src="~/assets/images/slider-img.png" alt="" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel_btn_box">
                <a class="carousel-control-prev" href="#customCarousel1" role="button" data-slide="prev">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#customCarousel1" role="button" data-slide="next">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </section>
    <!-- end slider section -->

    <!-- catagory section -->

    <section class="catagory_section layout_padding">
        <div class="catagory_container">
            <div class="container">
                <div class="heading_container heading_center">
                    <h2>Tài nguyên số</h2>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_computer.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5>Công nghệ thông tin</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_book.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5>Khoa học cơ bản</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_vtkt.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5>Vận tải kinh tế</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_cokhi.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5>Cơ khí</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_congtrinh.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5>Công trình</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="~/assets/images/tns_dientu.gif" alt="" />
                            </div>
                            <div class="detail-box">
                                <h5>Điện - Điện tử</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end catagory section -->

    <!-- about section -->

    <section class="about_section layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-13">
                    <div class="img-box">
                        <img src="~/assets/images/about-img.png" alt="" />
                    </div>
                </div>
                <div class="col-md-13">
                    <div class="detail-box">
                        <div class="heading_container">
                            <h2>Tin tức</h2>
                        </div>
                        <p>
                            Thư viện số có chức năng đảm bảo việc thu thập, lưu trữ và phổ biến, cung cấp tài liệu số phục vụ giảng dạy, học tập, nghiên cứu của cán bộ và sinh viên trong và ngoài trường. Hỗ trợ khai thác hiệu quả nguồn tài nguyên thông tin đáp ứng nhu cầu bạn đọc..
                            <br />Đồng thời cập nhật những tin tức và thông tin mới nhất về Trường Đại học Giao thông Vận tải Phân hiệu tại Tp.Hồ Chí Minh.
                        </p>
                        <a href=""> Read More </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end about section -->

    <!-- client section -->


    <!-- end client section -->

    <!-- blog section -->

    <section class="blog_section layout_padding" style="padding-top:20px">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>Tài liệu nổi bật</h2>
            </div>
            <div class="row" id="topRateDocList">
                




            </div>
        </div>
    </section>

    <!-- end blog section -->

    <!-- contact section -->

    <section class="contact_section layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-13">
                    <div class="heading_container">
                        <h2 class="">Feedback để tụi mình phát triển hơn nhé!!!</h2>
                    </div>
                    <form action="#">
                        <div>
                            <input type="text" placeholder="Họ và tên" />
                        </div>
                        <div>
                            <input type="email" placeholder="Email" />
                        </div>
                        <div>
                            <input type="text" placeholder="Số điện thoại" />
                        </div>
                        <div>
                            <input type="text" class="message-box" placeholder="Đôi điều bạn muốn nhắn gửi..." />
                        </div>
                        <div class="btn-box">
                            <button>GỬI</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-13">
                    <div class="img-box">
                        <img src="~/assets/images/contact-img.png" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end contact section -->
    @section Scripts {
<script>
    $(document).ready(function ()
    {
        LoadTopRateDoc();
    });
    function LoadTopRateDoc(){
        $.ajax({
            url: '/Home/LoadTopRateDoc',
            method: 'get',
            success: function(result){
                if(result.status == "ok"){
                    var str = '';
                    $.each(result.sachs, function(index, value){
                        str+= '<div class="col-md-6">';
                     str+= '<div class="box">';
                         str+= '<div class="img-box">';
                             str+= '<img src="images/products/'+ value.anh + '"alt="" />';
                             str+= '<h4 class="blog_date">';
                                 str+= '<span>'+ value.tacgia + '</span>';
                             str+= '</h4>';
                         str+= '</div>';
                         str+= '<div class="detail-box" style="min-height:150px">';
                             str+= '<h5 >'+ value.tensach + '</h5>';
                             str+= '<a href="/Tailieu/Details/' + value.masach + '?idlayout=1"> Xem thêm </a>';
                         str+= '</div>';
                     str+= '</div>';
                 str+= '</div>';
                    });

                    $('#topRateDocList').html(str);
                }
            },
            error: function(err){
                console.log(err);
            }
        });
    }
</script>
}